### ISSUE TITLE
clink update fails with "Failed to unzip the latest release"

### ISSUE THREAD

**Issue by MagicAndre1981** [chrisant996/clink#303]
I tried to update from .23 to .24 on Windows 8.1, but it fails:

```
C:\WINDOWS\system32>clink update
Checking latest version...
Downloading latest release...
Expanding zip file...
Failed to unzip the latest release.
```

**Comment by chrisant996** [comment]
> I tried to update from .23 to .24 on Windows 8.1, but it fails:
> 
> ```
> C:\WINDOWS\system32>clink update
> Checking latest version...
> Downloading latest release...
> Expanding zip file...
> Failed to unzip the latest release.
> ```

What does the following command report?

```cmd
%systemroot%\system32\windowspowershell\v1.0\powershell.exe -Command "$ProgressPreference='SilentlyContinue' ; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12 ; Invoke-WebRequest -UseBasicParsing https://api.github.com/repos/chrisant996/clink/releases/latest | Select-Object -ExpandProperty Content"
```

**Comment by MagicAndre1981** [comment]
I get a response, so TLS1.2 works:

`{"url":"https://api.github.com/repos/chrisant996/clink/releases/69738025","assets_url":"https://api.github.com/repos/chrisant996/clink/releases/69738025/assets","upload_url":"https://uploads.github.com/repos/chrisant996/clink/releases/69738025/assets{?name,label}","html_url":"https://github.com/chrisant996/clink/releases/tag/v1.3.24","id":69738025,"author":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"node_id":"RE_kwDOEZT_vc4EKB4p","tag_name":"v1.3.24","target_commitish":"master","name":"v1.3.24","draft":false,"prerelease":false,"created_at":"2022-06-17T17:42:50Z","published_at":"2022-06-17T17:58:07Z","assets":[{"url":"https://api.github.com/repos/chrisant996/clink/releases/assets/68800793","id":68800793,"node_id":"RA_kwDOEZT_vc4EGdEZ","name":"clink.1.3.24.a8a0d2.zip","label":null,"uploader":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"content_type":"application/x-zip-compressed","state":"uploaded","size":1724401,"download_count":4,"created_at":"2022-06-17T17:57:59Z","updated_at":"2022-06-17T17:58:00Z","browser_download_url":"https://github.com/chrisant996/clink/releases/download/v1.3.24/clink.1.3.24.a8a0d2.zip"},{"url":"https://api.github.com/repos/chrisant996/clink/releases/assets/68800799","id":68800799,"node_id":"RA_kwDOEZT_vc4EGdEf","name":"clink.1.3.24.a8a0d2_setup.exe","label":null,"uploader":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"content_type":"application/x-msdownload","state":"uploaded","size":1438087,"download_count":0,"created_at":"2022-06-17T17:58:00Z","updated_at":"2022-06-17T17:58:01Z","browser_download_url":"https://github.com/chrisant996/clink/releases/download/v1.3.24/clink.1.3.24.a8a0d2_setup.exe"},{"url":"https://api.github.com/repos/chrisant996/clink/releases/assets/68800800","id":68800800,"node_id":"RA_kwDOEZT_vc4EGdEg","name":"clink.1.3.24.a8a0d2_symbols.zip","label":null,"uploader":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"content_type":"application/x-zip-compressed","state":"uploaded","size":7721538,"download_count":0,"created_at":"2022-06-17T17:58:01Z","updated_at":"2022-06-17T17:58:02Z","browser_download_url":"https://github.com/chrisant996/clink/releases/download/v1.3.24/clink.1.3.24.a8a0d2_symbols.zip"}],"tarball_url":"https://api.github.com/repos/chrisant996/clink/tarball/v1.3.24","zipball_url":"https://api.github.com/repos/chrisant996/clink/zipball/v1.3.24","body":"**Oops, sorry:** If you see \"Unable to find latest release zip file\", then you will need to manually update to v1.3.23 or higher.\r\n\r\n**Recent highlights:**  The v1.3.13 release added features that make the [i.lua](https://github.com/chrisant996/clink/discussions/263) script possible.  Argmatchers can now be written to do match completion in directories other than the current directory.  Argmatchers can also be written to take a whole command line as an argument:  for example the built-in `cmd` argmatcher (`cmd some_command`).\r\n\r\n#### v1.3.24\r\n- Standardized the order in which `completions` directories are searched.\r\n- Fixed the second return value from `clink.popuplist()`, which was backwards by mistake.\r\n"}`

**Comment by UweKeim** [comment]
Can confirm.

Works on:

- Windows 11
- Windows Server 2022

Does not work on:

- Windows Server 2016

When it fails, it fails like this:

```cmd
C:\>clink update
Checking latest version...
Downloading latest release...
Expanding zip file...
Failed to unzip the latest release.
```

**Comment by chrisant996** [comment]
Can you attempt `clink update` and then upload the `clink.log` file?

Maybe on Win8.x Powershell doesn't support unzipping?
Powershell v5.0 is supposed to be present on Win7 and higher, and the Expand-Archive cmdlet requires v5.0 or greater.

Do you have Clink installed under Program Files?
Did you get a prompt for elevation?

**Comment by UweKeim** [comment]
In my case, the `clink.log` says:

```txt
6188 start_logger              154 ---- 2022/06/17 20:20:23.751 -------------------------------------------------
6188 start_logger              160 Host process is 'cmd.exe' (pid 24968)
6188 start_logger              164 DLL path is 'C:\Program Files (x86)\clink'
6188 start_logger              178 Windows version 10.0.14393 (x64)
6188 start_logger              181 Clink version 1.3.23.5d5aed (x64)
6188 host_cmd::validate        304 Host is not interactive; cancelling inject.
17b0 =?                          0 Clink updater: failed to unzip the latest release.
0508 history_db::compact      1494 History:  539 active, 167 deleted
```

**Comment by MagicAndre1981** [comment]
here is my log:

```
2728 start_logger              154 ---- 2022/06/17 20:25:36.007 -------------------------------------------------
2728 start_logger              160 Host process is 'cmd.exe' (pid 10024)
2728 start_logger              164 DLL path is 'C:\Program Files (x86)\clink'
2728 start_logger              178 Windows version 6.3.9600 (x64)
2728 start_logger              181 Clink version 1.3.23.5d5aed (x64)
2728 host_cmd::validate        304 Host is not interactive; cancelling inject.
2b80 =?                          0 Clink updater: failed to unzip the latest release.
27a8 history_db::compact      1494 History:  9998 active, 22 deleted

```

**Comment by chrisant996** [comment]
1. Can you try bypassing AutoRun and see if that makes a difference?

e.g. `cmd /d \myclinkdir\clink inject`

**Comment by UweKeim** [comment]
Hopefully, I did understand correctly what you suggested. 

This is what I did:

```cmd
C:\>cmd /d "c:\Program Files (x86)\clink\clink" inject
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\>clink update
Checking latest version...
Expanding zip file...
Failed to unzip the latest release.

C:\>
```

**Comment by chrisant996** [comment]
Ok what does this command report?

```cmd
%systemroot%\system32\windowspowershell\v1.0\powershell.exe -Command $ProgressPreference='SilentlyContinue' ; Expand-Archive -Force -LiteralPath "%temp%\clink\updater\v1.3.24.zip" -DestinationPath "c:\program files (x86)\clink" ; echo $error.count
```

**Comment by UweKeim** [comment]
This is the script and the result:

```cmd
C:\>%systemroot%\system32\windowspowershell\v1.0\powershell.exe -Command $ProgressPreference='SilentlyContinue' ; Expand-Archive -Force -LiteralPath "%temp%\clink\updater\v1.3.24.zip" -DestinationPath "c:\program files (x86)\clink" ; echo $error.count
x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:177
+ ... nk\updater\v1.3.24.zip -DestinationPath c:\program files (x86)\clink  ...
+                                                               ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

1

C:\>
```

Maybe the white space in the path to clink is the issue here?

**Comment by MagicAndre1981** [comment]
same for me, also CommandNotFoundException

**Comment by chrisant996** [comment]
Ah.  Cmd is stripping quotes.  😑  Must add another layer of quotes.

**Comment by chrisant996** [comment]
But that's not the problem, unless your %TEMP% directory name contains spaces.

Clink expands the zip file into `%TEMP%\clink\updater\v1.3.24` directory.

So the command I should have asked you to run is actually this:

```cmd
%systemroot%\system32\windowspowershell\v1.0\powershell.exe -Command $ProgressPreference='SilentlyContinue' ; Expand-Archive -Force -LiteralPath "%temp%\clink\updater\v1.3.24.zip" -DestinationPath "%temp%\clink\updater\v1.3.24" ; echo $error.count
```

**Comment by UweKeim** [comment]
OK, I ran the script:

```cmd
Microsoft Windows [Version 10.0.20348.768]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

Clink v1.3.24.a8a0d2
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink

C:\>%systemroot%\system32\windowspowershell\v1.0\powershell.exe -Command $ProgressPreference='Silentl
yContinue' ; Expand-Archive -Force -LiteralPath "%temp%\clink\updater\v1.3.24.zip" -DestinationPath "%temp%\clink\update
r\v1.3.24" ; echo $error.count
0

C:\>
```

**Comment by MagicAndre1981** [comment]
my temp has no space:

`C:\Users\André\AppData\Local\Temp\clink\updater`

but the zip in the folder has 0kb in size 🤔

**Comment by chrisant996** [comment]
Uh lol whoa.

So maybe the unzip algorithm in the Win8.x Powershell has a flaw, or maybe a network error corrupted the .zip file during download?

Can you upload the `%temp%\clink\updater\v1.3.24.zip` file here for inspection, to see if the file got corrupted?

**Comment by chrisant996** [comment]
> my temp has no space:
> 
> `C:\Users\André\AppData\Local\Temp\clink\updater`
> 
> but the zip in the folder has 0kb in size 🤔 

Oh, ok. So it somehow got interrupted or didn't download at all.

What happens if you delete the zip file and try `clink update` again?

**Comment by MagicAndre1981** [comment]
> What happens if you delete the zip file and try `clink update` again?

I already tried this and it always happens the same. zip is 0kb. What is the download command you use? I could run it and post any errors.

**Comment by MagicAndre1981** [comment]
under Windows 10 it works fine:

```
C:\WINDOWS\system32>clink update
Checking latest version...
Downloading latest release...
Expanding zip file...
Updated Clink to v1.3.24.


0624 start_logger              154 ---- 2022/06/18 20:56:48.662 -------------------------------------------------
0624 start_logger              160 Host process is 'cmd.exe' (pid 1572)
0624 start_logger              164 DLL path is 'C:\Program Files (x86)\clink'
0624 start_logger              178 Windows version 10.0.17763 (x64)
0624 start_logger              181 Clink version 1.3.23.5d5aed (x64)
0624 host_cmd::validate        304 Host is not interactive; cancelling inject.
1e2c =?                          0 Clink updater: updated Clink to v1.3.24.
24d0 history_db::compact      1494 History:  73 active, 66 deleted

```

**Comment by UweKeim** [comment]
It seems that [this is the `unzip` method](https://github.com/chrisant996/clink/blob/8d8470cd2a589f0d110166e2e89daf1e9a17990e/clink/app/scripts/update.lua#L110-L129).

**Comment by MagicAndre1981** [comment]
my zip is 0kb, so download is somehow broken on 8.1 🤔 🤷‍♂️

**Comment by MagicAndre1981** [comment]
on my Windows 10, where the update worked, I still see the update when I run `winget upgrade` . So maybe try to download the setup and run it silently to update clink without doing any unzipping.

**Comment by chrisant996** [comment]
I made the http call to check for latest release use TLS 1.2.
I did not make the http call to download the latest release use TLS 1.2.

/facepalm

**Comment by chrisant996** [comment]
Fixed by f724b0a8897ceaa8b6801d58f821fca5a56b0472.

**Comment by MagicAndre1981** [comment]
ok, will test this in next update to .26. 

But updatecheck doesn't find the .25 version:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Alle Rechte vorbehalten.

```
Clink v1.3.25.080a5d
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink

C:\WINDOWS\system32>clink update
Checking latest version...
No update available; local version v1.3.25 is not older than latest release v1.3.24.
```

**Comment by chrisant996** [comment]
> ok, will test this in next update to .26. 
> 
> But updatecheck doesn't find the .25 version:

Last time that happened, it was a GitHub service issue, most likely with cache replication delays.

**Comment by MagicAndre1981** [comment]
> Last time that happened, it was a GitHub service issue, most likely with cache replication delays.

I still see it. How long can this take? what about the `winget upgrade` issue? Should I open a new issue with the suggestion to switch to installer?

**Comment by chrisant996** [comment]
@MagicAndre1981 Does your Win10 computer see v1.3.25?

The fact that Clink is able to say "not older than latest release **v1.3.24**" means it successfully queried the github API for "get latest release", and github reported "v1.3.24" as the latest release.

Here is the github API link:  [https://api.github.com/repos/chrisant996/clink/releases/latest](https://api.github.com/repos/chrisant996/clink/releases/latest).

To see what github is reporting:
1. Open the link above.
2. Find "tag_name" -- that's the version number of the latest release reported by the github API.
3. Find "browser_download_url" -- that's the URL for downloading the zip file.

The fact that Clink is able to say "v1.3.24" shows that the API request succeeded, and reported "v1.3.24".  If the github API reports an inaccurate version, there is nothing Clink could do to fix whatever problem the github web site is encountering.

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 Does your Win10 computer see v1.3.25?

yes, I get .25 as latest release

```
Microsoft Windows [Version 10.0.17763.3046]
(c) 2018 Microsoft Corporation. Alle Rechte vorbehalten.

Clink v1.3.25.080a5d
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink

C:\WINDOWS\system32>clink update
Checking latest version...
No update available; local version v1.3.25 is not older than latest release v1.3.25.
```

> The fact that Clink is able to say "not older than latest release **v1.3.24**" means it successfully queried the github API for "get latest release", and **github reported "v1.3.24" as the latest release**.

> The fact that Clink is able to say "v1.3.24" shows that the API request succeeded, and reported "v1.3.24". If the github API reports an inaccurate version, there is nothing Clink could do to fix whatever problem the github web site is encountering.
> 
> EDIT: Maybe something is caching web requests and return old cached results -- maybe your ISP, maybe a proxy between you and github, maybe your employer, maybe malware detection software, maybe something else.

API reports .25 when opening it with Edge on 8.1:

```
{
  "url": "https://api.github.com/repos/chrisant996/clink/releases/69783361",
  "assets_url": "https://api.github.com/repos/chrisant996/clink/releases/69783361/assets",
  "upload_url": "[https://uploads.github.com/repos/chrisant996/clink/releases/69783361/assets{?name,label](https://uploads.github.com/repos/chrisant996/clink/releases/69783361/assets%7B?name,label)}",
  "html_url": "https://github.com/chrisant996/clink/releases/tag/v1.3.25",
  "id": 69783361,
  "author": {
    "login": "chrisant996",
    "id": 17440311,
    "node_id": "MDQ6VXNlcjE3NDQwMzEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/17440311?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/chrisant996",
    "html_url": "https://github.com/chrisant996",
    "followers_url": "https://api.github.com/users/chrisant996/followers",
    "following_url": "[https://api.github.com/users/chrisant996/following{/other_user](https://api.github.com/users/chrisant996/following%7B/other_user)}",
    "gists_url": "[https://api.github.com/users/chrisant996/gists{/gist_id](https://api.github.com/users/chrisant996/gists%7B/gist_id)}",
    "starred_url": "[https://api.github.com/users/chrisant996/starred{/owner}{/repo](https://api.github.com/users/chrisant996/starred%7B/owner%7D%7B/repo)}",
    "subscriptions_url": "https://api.github.com/users/chrisant996/subscriptions",
    "organizations_url": "https://api.github.com/users/chrisant996/orgs",
    "repos_url": "https://api.github.com/users/chrisant996/repos",
    "events_url": "[https://api.github.com/users/chrisant996/events{/privacy](https://api.github.com/users/chrisant996/events%7B/privacy)}",
    "received_events_url": "https://api.github.com/users/chrisant996/received_events",
    "type": "User",
    "site_admin": false
  },
  "node_id": "RE_kwDOEZT_vc4EKM9B",
  "tag_name": "v1.3.25",
  "target_commitish": "master",
  "name": "v1.3.25",
  "draft": false,
  "prerelease": false,
  "created_at": "2022-06-19T03:49:19Z",
  "published_at": "2022-06-19T03:56:34Z",
  "assets": [
    {
      "url": "https://api.github.com/repos/chrisant996/clink/releases/assets/68911881",
      "id": 68911881,
      "node_id": "RA_kwDOEZT_vc4EG4MJ",
      "name": "clink.1.3.25.080a5d.zip",
      "label": null,
      "uploader": {
        "login": "chrisant996",
        "id": 17440311,
        "node_id": "MDQ6VXNlcjE3NDQwMzEx",
        "avatar_url": "https://avatars.githubusercontent.com/u/17440311?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/chrisant996",
        "html_url": "https://github.com/chrisant996",
        "followers_url": "https://api.github.com/users/chrisant996/followers",
        "following_url": "[https://api.github.com/users/chrisant996/following{/other_user](https://api.github.com/users/chrisant996/following%7B/other_user)}",
        "gists_url": "[https://api.github.com/users/chrisant996/gists{/gist_id](https://api.github.com/users/chrisant996/gists%7B/gist_id)}",
        "starred_url": "[https://api.github.com/users/chrisant996/starred{/owner}{/repo](https://api.github.com/users/chrisant996/starred%7B/owner%7D%7B/repo)}",
        "subscriptions_url": "https://api.github.com/users/chrisant996/subscriptions",
        "organizations_url": "https://api.github.com/users/chrisant996/orgs",
        "repos_url": "https://api.github.com/users/chrisant996/repos",
        "events_url": "[https://api.github.com/users/chrisant996/events{/privacy](https://api.github.com/users/chrisant996/events%7B/privacy)}",
        "received_events_url": "https://api.github.com/users/chrisant996/received_events",
        "type": "User",
        "site_admin": false
      },
      "content_type": "application/x-zip-compressed",
      "state": "uploaded",
      "size": 1725099,
      "download_count": 426,
      "created_at": "2022-06-19T03:56:27Z",
      "updated_at": "2022-06-19T03:56:29Z",
      "browser_download_url": "https://github.com/chrisant996/clink/releases/download/v1.3.25/clink.1.3.25.080a5d.zip"
    },
    {
      "url": "https://api.github.com/repos/chrisant996/clink/releases/assets/68911883",
      "id": 68911883,
      "node_id": "RA_kwDOEZT_vc4EG4ML",
      "name": "clink.1.3.25.080a5d_setup.exe",
      "label": null,
      "uploader": {
        "login": "chrisant996",
        "id": 17440311,
        "node_id": "MDQ6VXNlcjE3NDQwMzEx",
        "avatar_url": "https://avatars.githubusercontent.com/u/17440311?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/chrisant996",
        "html_url": "https://github.com/chrisant996",
        "followers_url": "https://api.github.com/users/chrisant996/followers",
        "following_url": "[https://api.github.com/users/chrisant996/following{/other_user](https://api.github.com/users/chrisant996/following%7B/other_user)}",
        "gists_url": "[https://api.github.com/users/chrisant996/gists{/gist_id](https://api.github.com/users/chrisant996/gists%7B/gist_id)}",
        "starred_url": "[https://api.github.com/users/chrisant996/starred{/owner}{/repo](https://api.github.com/users/chrisant996/starred%7B/owner%7D%7B/repo)}",
        "subscriptions_url": "https://api.github.com/users/chrisant996/subscriptions",
        "organizations_url": "https://api.github.com/users/chrisant996/orgs",
        "repos_url": "https://api.github.com/users/chrisant996/repos",
        "events_url": "[https://api.github.com/users/chrisant996/events{/privacy](https://api.github.com/users/chrisant996/events%7B/privacy)}",
        "received_events_url": "https://api.github.com/users/chrisant996/received_events",
        "type": "User",
        "site_admin": false
      },
      "content_type": "application/x-msdownload",
      "state": "uploaded",
      "size": 1438911,
      "download_count": 174,
      "created_at": "2022-06-19T03:56:29Z",
      "updated_at": "2022-06-19T03:56:29Z",
      "browser_download_url": "https://github.com/chrisant996/clink/releases/download/v1.3.25/clink.1.3.25.080a5d_setup.exe"
    },
    {
      "url": "https://api.github.com/repos/chrisant996/clink/releases/assets/68911884",
      "id": 68911884,
      "node_id": "RA_kwDOEZT_vc4EG4MM",
      "name": "clink.1.3.25.080a5d_symbols.zip",
      "label": null,
      "uploader": {
        "login": "chrisant996",
        "id": 17440311,
        "node_id": "MDQ6VXNlcjE3NDQwMzEx",
        "avatar_url": "https://avatars.githubusercontent.com/u/17440311?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/chrisant996",
        "html_url": "https://github.com/chrisant996",
        "followers_url": "https://api.github.com/users/chrisant996/followers",
        "following_url": "[https://api.github.com/users/chrisant996/following{/other_user](https://api.github.com/users/chrisant996/following%7B/other_user)}",
        "gists_url": "[https://api.github.com/users/chrisant996/gists{/gist_id](https://api.github.com/users/chrisant996/gists%7B/gist_id)}",
        "starred_url": "[https://api.github.com/users/chrisant996/starred{/owner}{/repo](https://api.github.com/users/chrisant996/starred%7B/owner%7D%7B/repo)}",
        "subscriptions_url": "https://api.github.com/users/chrisant996/subscriptions",
        "organizations_url": "https://api.github.com/users/chrisant996/orgs",
        "repos_url": "https://api.github.com/users/chrisant996/repos",
        "events_url": "[https://api.github.com/users/chrisant996/events{/privacy](https://api.github.com/users/chrisant996/events%7B/privacy)}",
        "received_events_url": "https://api.github.com/users/chrisant996/received_events",
        "type": "User",
        "site_admin": false
      },
      "content_type": "application/x-zip-compressed",
      "state": "uploaded",
      "size": 7707377,
      "download_count": 8,
      "created_at": "2022-06-19T03:56:29Z",
      "updated_at": "2022-06-19T03:56:31Z",
      "browser_download_url": "https://github.com/chrisant996/clink/releases/download/v1.3.25/clink.1.3.25.080a5d_symbols.zip"
    }
  ],
  "tarball_url": "https://api.github.com/repos/chrisant996/clink/tarball/v1.3.25",
  "zipball_url": "https://api.github.com/repos/chrisant996/clink/zipball/v1.3.25",
  "body": "**Oops, sorry:** If you see \"Unable to find latest release zip file\" or \"Failed to unzip the latest release\", then you will need to manually update to v1.3.25 or higher (this should only affects Windows 8.x users).\r\n\r\n**Recent highlights:**  The v1.3.13 release added features that make the [i.lua](https://github.com/chrisant996/clink/discussions/263) script possible.  Argmatchers can now be written to do match completion in directories other than the current directory.  Argmatchers can also be written to take a whole command line as an argument:  for example the built-in `cmd` argmatcher (`cmd some_command`).\r\n\r\n#### v1.3.25\r\n- Fixed updater when `%TEMP%` contains spaces.\r\n- Fixed executable file detection to color device names (such as nul, aux, con, lpt1, and com1) as neither recognized nor unrecognized.\r\n- Fixed [#304](https://github.com/chrisant996/clink/issues/304); hang when typing device names (such as aux, con, lpt1, and com1) (regression introduced in v1.3.23).\r\n- Fixed [#303](https://github.com/chrisant996/clink/issues/303); downloading latest update doesn't work on Windows 8.x.\r\n",
  "reactions": {
    "url": "https://api.github.com/repos/chrisant996/clink/releases/69783361/reactions",
    "total_count": 3,
    "+1": 3,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  }
}
```

**Comment by MagicAndre1981** [comment]
Both devices are on same network, use same ISP (German Telekom) and have both NOD32 installed. I will ignore this for now 🤷‍♂️

**Comment by chrisant996** [comment]
Are you saying Clink is still saying v1.3.24 is the latest, while a browser says v1.3.25 is the latest?

I don't see how that could be Clink's fault, and I'm unable to reproduce it.

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 Are you saying Clink is still saying v1.3.24 is the latest, even some days later, while a browser says v1.3.25 is the latest?

yes, still today. I have no idea why this is so

**Comment by UweKeim** [comment]
@MagicAndre1981 How about using [Fiddler](https://www.telerik.com/download/fiddler) on your system to see what requests (URL, headers and payload) are sent and which responses (headers and payload) are returned.

Maybe this gives you a better clue about whether the internal processing of the update script fails or whether the wrong data arrive from the servers?

**Comment by pukkandan** [comment]
What do you get if you run this in powershell?
```
Invoke-WebRequest https://api.github.com/repos/chrisant996/clink/releases/latest | Select-Object -ExpandProperty Content
```

**Comment by MagicAndre1981** [comment]
> Maybe this gives you a better clue about whether the internal processing of the update script fails or whether the wrong data arrive from the servers?

I tried Charles as I used it a few times compared to fiddler, but I fail to tell powershell to use the Charles certificate to intercept SSL communication and look at the response.

When I run this command from powershell I see .25, but not when I run `clink update` 🤔 🤷‍♂️

`{"url":"https://api.github.com/repos/chrisant996/clink/releases/69783361","assets_url":"https://api.github.com/repos/chrisant996/clink/releases/69783361/assets","upload_url":"https://uploads.github.com/repos/chrisant996/clink/releases/69783361/assets{?name,label}","html_url":"https://github.com/chrisant996/clink/releases/tag/v1.3.25","id":69783361,"author":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"node_id":"RE_kwDOEZT_vc4EKM9B","tag_name":"v1.3.25","target_commitish":"master","name":"v1.3.25","draft":false,"prerelease":false,"created_at":"2022-06-19T03:49:19Z","published_at":"2022-06-19T03:56:34Z","assets":[{"url":"https://api.github.com/repos/chrisant996/clink/releases/assets/68911881","id":68911881,"node_id":"RA_kwDOEZT_vc4EG4MJ","name":"clink.1.3.25.080a5d.zip","label":null,"uploader":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"content_type":"application/x-zip-compressed","state":"uploaded","size":1725099,"download_count":599,"created_at":"2022-06-19T03:56:27Z","updated_at":"2022-06-19T03:56:29Z","browser_download_url":"https://github.com/chrisant996/clink/releases/download/v1.3.25/clink.1.3.25.080a5d.zip"},{"url":"https://api.github.com/repos/chrisant996/clink/releases/assets/68911883","id":68911883,"node_id":"RA_kwDOEZT_vc4EG4ML","name":"clink.1.3.25.080a5d_setup.exe","label":null,"uploader":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"content_type":"application/x-msdownload","state":"uploaded","size":1438911,"download_count":266,"created_at":"2022-06-19T03:56:29Z","updated_at":"2022-06-19T03:56:29Z","browser_download_url":"https://github.com/chrisant996/clink/releases/download/v1.3.25/clink.1.3.25.080a5d_setup.exe"},{"url":"https://api.github.com/repos/chrisant996/clink/releases/assets/68911884","id":68911884,"node_id":"RA_kwDOEZT_vc4EG4MM","name":"clink.1.3.25.080a5d_symbols.zip","label":null,"uploader":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"content_type":"application/x-zip-compressed","state":"uploaded","size":7707377,"download_count":12,"created_at":"2022-06-19T03:56:29Z","updated_at":"2022-06-19T03:56:31Z","browser_download_url":"https://github.com/chrisant996/clink/releases/download/v1.3.25/clink.1.3.25.080a5d_symbols.zip"}],"tarball_url":"https://api.github.com/repos/chrisant996/clink/tarball/v1.3.25","zipball_url":"https://api.github.com/repos/chrisant996/clink/zipball/v1.3.25","body":"**Oops, sorry:** If you see \"Unable to find latest release zip file\" or \"Failed to unzip the latest release\", then you will need to manually update to v1.3.25 or higher (this should only affects Windows 8.x users).\r\n\r\n**Recent highlights:**  The v1.3.13 release added features that make the [i.lua](https://github.com/chrisant996/clink/discussions/263) script possible.  Argmatchers can now be written to do match completion in directories other than the current directory.  Argmatchers can also be written to take a whole command line as an argument:  for example the built-in `cmd` argmatcher (`cmd some_command`).\r\n\r\n#### v1.3.25\r\n- Fixed updater when `%TEMP%` contains spaces.\r\n- Fixed executable file detection to color device names (such as nul, aux, con, lpt1, and com1) as neither recognized nor unrecognized.\r\n- Fixed [#304](https://github.com/chrisant996/clink/issues/304); hang when typing device names (such as aux, con, lpt1, and com1) (regression introduced in v1.3.23).\r\n- Fixed [#303](https://github.com/chrisant996/clink/issues/303); downloading latest update doesn't work on Windows 8.x.\r\n","reactions":{"url":"https://api.github.com/repos/chrisant996/clink/releases/69783361/reactions","total_count":3,"+1":3,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0}}`

**Comment by chrisant996** [comment]
Thank you, @pukkandan !

The `Invoke-WebRequest` cmdlet defaults to including this header:
```
Cache-Control                 public, max-age=60, s-maxage=60
```

On Win10, that doesn't prevent Powershell from validating the cached results and re-fetching the latest.

But perhaps on Win8.x the older version of Powershell returns cached results in some cases?

I've added `cache-control=no-cache` and maybe that will help on @MagicAndre1981 's Win8.x computer.

**Comment by pukkandan** [comment]
> But perhaps on Win8.x the older version of Powershell returns cached results in some cases?

I thought so as well, but from their response, it doesn't look like it

> When I run this command from powershell I see .25, but not when I run clink update 🤔 🤷‍♂️

**Comment by MagicAndre1981** [comment]
> I've added `cache-control=no-cache` and maybe that will help on @MagicAndre1981 's Win8.x computer.

this time, the installed .25 finds the .26 release, downloads the zip (this time not 0kb), but I still see "Failed to unzip the latest release".

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Alle Rechte vorbehalten.

Clink v1.3.25.080a5d
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink

C:\WINDOWS\system32>clink update
Checking latest version...
Downloading latest release...
Expanding zip file...
Failed to unzip the latest release.

C:\WINDOWS\system32>


1450 start_logger              154 ---- 2022/06/23 07:19:57.818 -------------------------------------------------
1450 start_logger              160 Host process is 'cmd.exe' (pid 5200)
1450 start_logger              164 DLL path is 'C:\Program Files (x86)\clink'
1450 start_logger              178 Windows version 6.3.9600 (x64)
1450 start_logger              181 Clink version 1.3.25.080a5d (x64)
1450 host_cmd::validate        304 Host is not interactive; cancelling inject.
21e4 =?                          0 Clink updater: failed to unzip the latest release.
1c38 history_db::compact      1494 History:  9990 active, 66 deleted

```
I compared the hash of the downloaded zip in temp and my manually downloaded zip and both match, so download is not corrupted. 

![clink_hash_26](https://user-images.githubusercontent.com/8274816/175224419-f235949b-7ba2-46d3-87ba-4195940d3230.png)


So there is still an issue with the unzip code.

**Comment by UweKeim** [comment]
Same here on my Windows Server 2016:

```txt
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

Clink v1.3.24.a8a0d2
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink

Clink v1.3.26 is available.
- To apply the update, run 'clink update'.
- To stop checking for updates, run 'clink set clink.autoupdate false'.
- To view the release notes, visit the Releases page:
  https://github.com/chrisant996/clink/releases

C:\>clink update
Checking latest version...
Expanding zip file...
Failed to unzip the latest release.

C:\>
```

**Comment by chrisant996** [comment]
I see that @MagicAndre1981 has Clink installed for autorun.

@UweKeim do you also have Clink installed for autorun?

What happens if you disable autorun?
`clink autorun uninstall`

**Comment by MagicAndre1981** [comment]
> What happens if you disable autorun? `clink autorun uninstall`
> 
> And then update? `clink update`

I still get the same error message after autorun uninstall

**Comment by MagicAndre1981** [comment]
can you please post the powershell command you use to expand the zip? Maybe running it normally shows more details what is wrong.

**Comment by MagicAndre1981** [comment]
> Looking at the folder mentioned in the log file:
> 
> ![image](https://user-images.githubusercontent.com/415439/175236433-2539446f-8b89-428e-b85e-9c39b6ae10b0.png)

strange, in your case the file is still 0kb, so nothing to unzip. So the download is still an issue for you and I have unzip issues.

**Comment by UweKeim** [comment]
Now I've manually installed `v1.3.26` on my Windows Server 2016. 

Maybe this fixed some download issues.

Will try again when `v1.3.27` comes out, whether works better.

**Comment by UweKeim** [comment]
Crazy! This version works correctly on my Windows Server 2016!

```txt
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

Clink v0.0.1.7c097e
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink

Clink v1.3.26 is available.
- To apply the update, run 'clink update'.
- To stop checking for updates, run 'clink set clink.autoupdate false'.
- To view the release notes, visit the Releases page:
  https://github.com/chrisant996/clink/releases

C:\>clink update
Checking latest version...
Expanding zip file...
Updating registry keys...
Updated Clink to v1.3.26.

C:\>
```

The `clink.log` contains:

```txt
7d98 start_logger              154 ---- 2022/06/23 19:41:30.374 -------------------------------------------------
7d98 start_logger              160 Host process is 'cmd.exe' (pid 32152)
7d98 start_logger              164 DLL path is 'C:\Program Files (x86)\clink'
7d98 start_logger              178 Windows version 10.0.14393 (x64)
7d98 start_logger              181 Clink version 1.3.26.eec90c (x64)
7d98 host_cmd::validate        304 Host is not interactive; cancelling inject.
532c =?                          0 Clink updater: updated Clink to v1.3.26.
5910 history_db::compact      1494 History:  543 active, 181 deleted
```

**Comment by MagicAndre1981** [comment]
ok, this helped. [Expand-Archive](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-7.2) is not found as command:

```
0df0 start_logger              154 ---- 2022/06/23 19:41:33.895 -------------------------------------------------
0df0 start_logger              160 Host process is 'cmd.exe' (pid 3568)
0df0 start_logger              164 DLL path is 'C:\Program Files (x86)\clink'
0df0 start_logger              178 Windows version 6.3.9600 (x64)
0df0 start_logger              181 Clink version 0.0.1.7c097e (x64)
0df0 host_cmd::validate        304 Host is not interactive; cancelling inject.
0a98 =?                          0 Clink updater: 2>&1 "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -Command $ProgressPreference='SilentlyContinue' ; Expand-Archive -Force -LiteralPath \"C:\Users\ANDR~1\AppData\Local\Temp\clink\updater\v1.3.26.zip\" -DestinationPath \"C:\Users\ANDR~1\AppData\Local\Temp\clink\updater\v1.3.26\" ; echo $error.count
0a98 =?                          0 Clink updater: output from command:
0a98 =?                          0 Clink updater:     Expand-Archive : Die Benennung "Expand-Archive" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines 
0a98 =?                          0 Clink updater:     ausfhrbaren Programms erkannt. šberprfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und 
0a98 =?                          0 Clink updater:     wiederholen Sie den Vorgang.
0a98 =?                          0 Clink updater:     In Zeile:1 Zeichen:42
0a98 =?                          0 Clink updater:     + $ProgressPreference='SilentlyContinue' ; Expand-Archive -Force -LiteralPath "C:\ ...
0a98 =?                          0 Clink updater:     +                                          ~~~~~~~~~~~~~~
0a98 =?                          0 Clink updater:         + CategoryInfo          : ObjectNotFound: (Expand-Archive:String) [], CommandNotFoundException
0a98 =?                          0 Clink updater:         + FullyQualifiedErrorId : CommandNotFoundException
0a98 =?                          0 Clink updater:      
0a98 =?                          0 Clink updater:     1
0a98 =?                          0 Clink updater: failed to unzip the latest release.
15e0 history_db::compact      1494 History:  9995 active, 68 deleted

```

**Comment by chrisant996** [comment]
😑

I will look for a way to check the Powershell version and report an informative error message.

😑

**Comment by MagicAndre1981** [comment]
it works: 🥰🥳

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Alle Rechte vorbehalten.

Clink v0.0.1.7c097e
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink

Clink v1.3.26 is available.
- To apply the update, run 'clink update'.
- To stop checking for updates, run 'clink set clink.autoupdate false'.
- To view the release notes, visit the Releases page:
  https://github.com/chrisant996/clink/releases

C:\WINDOWS\system32>clink update
Checking latest version...
Expanding zip file...
Updating registry keys...
Updated Clink to v1.3.26.
```

so yes, check for PS 5.1 on Win7, 8.1, Server 2008 R2, Server 2012 R2 systems to avoid this

**Comment by UweKeim** [comment]
Thanks for all your efforts, @chrisant996, highly appreciated by me!

I'm only using the built-in Windows Defender, no 3rd party snake oil. So I _hope_ this does not interfer.

**Comment by chrisant996** [comment]
@UweKeim @MagicAndre1981 can one of you try `powershell Get-Host` with German as the current UI language?  I want to make sure that the field names always show up in English, so that they can be used programmatically.  Particularly the "Version" field.

**Comment by chrisant996** [comment]
Phew.  I expect the updater in v1.3.27 will finally work on Win8.x.  But we'll have to wait until v1.3.28 to know for certain, of course.

I also noticed that the PowerShell output in the log file showed up with the wrong encoding, so I added a Lua API for codepage/UTF8 conversion so that the log file can contain accurate output from the PowerShell commands.  And the functions can be used for output from other programs in general -- in fact, for any programs whose output is in the current Active Code Page rather than UTF8.  Lua scripts must explicitly use `unicode.fromcodepage(text)` to do it, though, there's no good way to safely do it automatically.

**Comment by MagicAndre1981** [comment]
> @UweKeim @MagicAndre1981 can one of you try `powershell -Command Get-Host` with German as the current UI language? 

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Alle Rechte vorbehalten.

Clink v1.3.26.eec90c
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink

C:\Users\André>powershell -Command Get-Host


Name             : ConsoleHost
Version          : 5.1.14409.1027
InstanceId       : b6d9e103-068f-4633-b404-e56ffd57b3b0
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : de-DE
CurrentUICulture : de-DE
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

I did the update to .27, but now I see an error:

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Alle Rechte vorbehalten.

Clink v1.3.27.cc94e1
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink

?:0: attempt to compare nil with number
C:\WINDOWS\system32>clink update
?:0: attempt to compare nil with number
The update attempt failed for an unknown reason.

C:\WINDOWS\system32>
```

**Comment by chrisant996** [comment]
I think the Powershell version check is failing when the UI language is not English.

That issue is tracked by #309.

**Comment by MagicAndre1981** [comment]
> It's fixed in v1.3.32.

ok, [update to .32 is somehow broken](https://github.com/chrisant996/clink/issues/313)

**Comment by captainkirkoff** [comment]
Hi,
I'm still experiencing thiss issue with 1.3.31.
It happens with my work PC (Win 10.0.19044.1766) while not happening with my home PC (Window 11).
Italian UI in both cases.
The console message says "Failed to unzip the latest release", but that's not properly true because I find all files completely unzipped under AppData\Local\clink\updater\v1.3.33\. 
This is the log:
```
2368 start_logger              157 ---- 2022/07/01 11:52:28.344 -------------------------------------------------
2368 start_logger              163 Host process is 'cmd.exe' (pid 9064)
2368 start_logger              167 DLL path is 'C:\Program Files (x86)\clink'
2368 start_logger              181 Windows version 10.0.19044 (x64)
2368 start_logger              184 Clink version 1.3.31.f14c84 (x64)
2368 host_cmd::validate        304 Host is not interactive; cancelling inject.
3ee4 =?                          0 Clink updater: 2>&1 "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -Command $ProgressPreference='SilentlyContinue' ; Expand-Archive -Force -LiteralPath \"C:\Users\piero\AppData\Local\Temp\clink\updater\v1.3.33.zip\" -DestinationPath \"C:\Users\piero\AppData\Local\Temp\clink\updater\v1.3.33\" ; echo $error.count
3ee4 =?                          0 Clink updater: output from command:
3ee4 =?                          0 Clink updater:     1
3ee4 =?                          0 Clink updater:     
3ee4 =?                          0 Clink updater: failed to unzip the latest release.
```

![image](https://user-images.githubusercontent.com/6802846/176874139-31316780-76fc-4fa8-aee7-0efaf67cbfa1.png)

**Comment by chrisant996** [comment]
> Hi,
> I'm still experiencing thiss issue with 1.3.31.
> It happens with my work PC (Win 10.0.19044.1766) while not happening with my home PC (Window 11).
> Italian UI in both cases.
> The console message says "Failed to unzip the latest release", but that's not properly true because I find all files completely unzipped under AppData\Local\clink\updater\v1.3.33\. 
> This is the log:
> ```
> ...
> 3ee4 =?                          0 Clink updater: 2>&1 "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -Command $ProgressPreference='SilentlyContinue' ; Expand-Archive -Force -LiteralPath \"C:\Users\piero\AppData\Local\Temp\clink\updater\v1.3.33.zip\" -DestinationPath \"C:\Users\piero\AppData\Local\Temp\clink\updater\v1.3.33\" ; echo $error.count
> 3ee4 =?                          0 Clink updater: output from command:
> 3ee4 =?                          0 Clink updater:     1
> ...
> ```

See the `1` output in the log?
That is the count of errors reported by PowerShell when it expands the zip file.

Try manually running the Powershell command that's listed in the log: what happens when you run it manually?

**Comment by chrisant996** [comment]
The `$error` contains all errors that have occurred in the current PowerShell session.

Can you run the following command?  Please do not strip the $error parts -- they are an important part of the command, especially for troubleshooting purposes.

```cmd
"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -Command $ProgressPreference='SilentlyContinue' ; Expand-Archive -Force -LiteralPath "C:\Users\piero\AppData\Local\Temp\clink\updater\v1.3.33.zip" -DestinationPath "C:\Users\piero\AppData\Local\Temp\clink\updater\v1.3.33" ; echo $error.count ; echo $error
```

**Comment by captainkirkoff** [comment]
Ok, here's the output (sorry, I'm totally ignorant about PowerShell):
![image](https://user-images.githubusercontent.com/6802846/176959025-887cf449-fd74-41b4-8519-20cb7144731d.png)

**Comment by MagicAndre1981** [comment]
remove this [3rd party module "Jump.Location"](https://www.powershellgallery.com/packages/Jump.Location/0.6.0) and try again

**Comment by chrisant996** [comment]
@captainkirkoff ah, excellent, thank you.  Yes, there is indeed some configuration problem with PowerShell on that computer. Apparently an error occurs in a script that automatically runs during PowerShell startup.

I have a change coming in Clink that will make it resilient to that kind of problem.

**Comment by captainkirkoff** [comment]
> @captainkirkoff ah, excellent, thank you. Yes, there is indeed some configuration problem with PowerShell on that computer. 

Yes! And as @MagicAndre1981 suggests, removing that module everything goes fine.
I don't even remember why I installed it, that's enough to say I don't need it. ;-)

By the way, thank you for this wonderful piece of software. :-)

**Comment by Welding-Torch** [comment]
Got this same problem right now in 2024. Quite odd considering that the last few Clink updates installed smoothly.

**Comment by chrisant996** [comment]
Check whether your anti virus tool is interfering. Some people have reported that some anti virus tools are getting false positives.

Also check the clink.log file to see if it lists any info about what failed.

**Comment by Welding-Torch** [comment]
Indeed you are right, Windows Defender's Protection History shows that it was removing the `\clink\updater\v1.6.0.zip` before it could be unzipped. 

Overactive Antivirus smh. Thanks for the help, Chris.
